# Start the testnet server with the command 'docker-compose up -d'

bchjs:
  build: ./production/
  dockerfile: Dockerfile
  container_name: bchjs
  ports:
    - "5210:3210"  # <host port>:<container port>
    - "5001:4001"  # IPFS
  volumes:
    - ./ipfs-data:/home/safeuser/koa-ipfs-bchjs/ipfs-data
  restart: always

tor:
  image: goldy/tor-hidden-service
  container_name: tor-bchjs
  links:
    - bchjs
  environment:
      BCHJS_PORTS: 80:3210 # Map port to detected service
  volumes:
    - ./keys:/var/lib/tor/hidden_service/
  restart: always
