# Start the testnet server with the command 'docker-compose up -d'

koa:
  build: ./production/
  dockerfile: Dockerfile
  container_name: koa-ipfs
  ports:
    - "3210:3210"  # <host port>:<container port>
    - "4001:4001"  # IPFS
  volumes:
#    - ./ipfs-config:/home/safeuser/.ipfs
    - ./ipfs-data:/home/safeuser/koa-ipfs-blog/ipfs-data
#    - ./logs:/home/coinjoin/consolidating-coinjoin/logs
    #- ./keys:/home/safeuser/keys
#  links:
#    - ipfs
  restart: always

tor:
  image: goldy/tor-hidden-service
  container_name: tor
  links:
    - koa
  environment:
      KOA_PORTS: 80:3210 # Map port to detected service
  volumes:
    - ./keys:/var/lib/tor/hidden_service/
  restart: always
